#!/usr/bin/env node

const { logError, printHelp, ask } = require('./utils');
const TodosController = require('./todosController');

const args = process.argv.slice(2);
const command = args[0];

const routes = {
  help: () => printHelp(),
  list: () => TodosController.index( ...args.slice(1) ),
  new: () => TodosController.new( ...args.slice(1) ),
  complete: () => TodosController.complete( ...args.slice(1) ),
};

if (routes.hasOwnProperty(command)) {
  routes[command]();
} else {
  logError(`ERROR: Invalid command '${command}'`);
  printHelp();
  process.exit(1);
}
